export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',
  STAFF: 'STAFF',
  PATIENT: 'PATIENT'
};

export const PERMISSIONS = {
  MANAGE_SYSTEM: 'MANAGE_SYSTEM', // Süper Admin yetkisi
  MANAGE_CLINIC: 'MANAGE_CLINIC',
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  MANAGE_PATIENTS: 'MANAGE_PATIENTS',
  MANAGE_APPOINTMENTS: 'MANAGE_APPOINTMENTS',
  MANAGE_FINANCE: 'MANAGE_FINANCE',
  MANAGE_USERS: 'MANAGE_USERS',
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.MANAGE_SYSTEM,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_CLINIC,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_FINANCE
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_CLINIC,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_PATIENTS,
    PERMISSIONS.MANAGE_APPOINTMENTS,
    PERMISSIONS.MANAGE_FINANCE,
    PERMISSIONS.MANAGE_USERS
  ],
  [ROLES.DOCTOR]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_PATIENTS,
    PERMISSIONS.MANAGE_APPOINTMENTS
  ],
  [ROLES.STAFF]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_APPOINTMENTS
  ]
};