export const ROLES = {
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',
  SECRETARY: 'SECRETARY',
  ASSISTANT: 'ASSISTANT',
  ACCOUNTANT: 'ACCOUNTANT',
};

export const PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_FINANCIALS: 'VIEW_FINANCIALS',
  MANAGE_APPOINTMENTS: 'MANAGE_APPOINTMENTS',
  VIEW_PATIENT_RECORDS: 'VIEW_PATIENT_RECORDS',
  EDIT_PATIENT_RECORDS: 'EDIT_PATIENT_RECORDS',
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS), // Admin her şeyi yapabilir
  [ROLES.DOCTOR]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_APPOINTMENTS,
    PERMISSIONS.VIEW_PATIENT_RECORDS,
    PERMISSIONS.EDIT_PATIENT_RECORDS,
  ],
  [ROLES.SECRETARY]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_APPOINTMENTS,
    PERMISSIONS.VIEW_PATIENT_RECORDS,
  ],
  [ROLES.ASSISTANT]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_PATIENT_RECORDS,
  ],
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_FINANCIALS,
  ],
};