
-- clinic_expenses tablosunu oluştur
CREATE TABLE public.clinic_expenses (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    clinic_id uuid NOT NULL,
    description text NOT NULL,
    amount numeric NOT NULL,
    expense_date date NOT NULL DEFAULT now(),
    is_deleted boolean DEFAULT false,
    deleted_at timestamp with time zone,
    CONSTRAINT clinic_expenses_pkey PRIMARY KEY (id),
    CONSTRAINT clinic_expenses_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE
);

-- RLS'yi etkinleştir
ALTER TABLE public.clinic_expenses ENABLE ROW LEVEL SECURITY;

-- Mevcut satırları görünebilir yap
ALTER TABLE public.clinic_expenses OWNER TO postgres;

-- Tabloya erişim yetkilerini düzenle
GRANT ALL ON TABLE public.clinic_expenses TO anon;
GRANT ALL ON TABLE public.clinic_expenses TO authenticated;
GRANT ALL ON TABLE public.clinic_expenses TO postgres;
GRANT ALL ON TABLE public.clinic_expenses TO service_role;

-- Giderlerin sadece ilgili klinik üyeleri tarafından görülebilmesi için RLS politikası
CREATE POLICY "Enable read access for clinic members" ON public.clinic_expenses
AS PERMISSIVE FOR SELECT
TO authenticated
USING (
  (SELECT clinic_id FROM public.profiles WHERE id = auth.uid()) = clinic_id
);

-- Gider ekleme işleminin sadece ilgili klinik üyeleri tarafından yapılabilmesi için RLS politikası
CREATE POLICY "Enable insert for clinic members" ON public.clinic_expenses
AS PERMISSIVE FOR INSERT
TO authenticated
WITH CHECK (
  (SELECT clinic_id FROM public.profiles WHERE id = auth.uid()) = clinic_id
);

-- Gider güncelleme işleminin sadece ilgili klinik üyeleri tarafından yapılabilmesi için RLS politikası
CREATE POLICY "Enable update for clinic members" ON public.clinic_expenses
AS PERMISSIVE FOR UPDATE
TO authenticated
USING (
  (SELECT clinic_id FROM public.profiles WHERE id = auth.uid()) = clinic_id
)
WITH CHECK (
  (SELECT clinic_id FROM public.profiles WHERE id = auth.uid()) = clinic_id
);

-- Gider silme (soft delete) işleminin sadece ilgili klinik üyeleri tarafından yapılabilmesi için RLS politikası
CREATE POLICY "Enable soft delete for clinic members" ON public.clinic_expenses
AS PERMISSIVE FOR UPDATE
TO authenticated
USING (
  (SELECT clinic_id FROM public.profiles WHERE id = auth.uid()) = clinic_id
)
WITH CHECK (is_deleted = true);

-- Gerçek silme işlemini engellemek için RLS politikası
CREATE POLICY "Prevent hard delete" ON public.clinic_expenses
AS PERMISSIVE FOR DELETE
TO authenticated
USING (false);
